# Generated by Django 4.1.6 on 2023-02-17 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='garantia',
            fields=[
                ('id_garantia', models.AutoField(primary_key=True, serialize=False)),
                ('valor_tasacion', models.FloatField()),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=256)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('tasa', models.FloatField()),
                ('cuota', models.FloatField()),
                ('estado', models.CharField(max_length=30)),
                ('clasificacion', models.CharField(max_length=30)),
                ('porciento_mora', models.FloatField()),
                ('dias_gracia', models.IntegerField()),
                ('id_solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=80)),
                ('id_garantia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.garantia')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=40)),
                ('monto', models.FloatField()),
                ('cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='prestamo_garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_garantia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.garantia')),
                ('id_prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
                ('monto_total', models.FloatField(unique=True)),
                ('monto_interes', models.FloatField(unique=True)),
                ('monto_capital', models.FloatField(unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=40)),
                ('id_prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='informacion_trabajo',
            fields=[
                ('id_info', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=256)),
                ('sueldo', models.FloatField()),
                ('cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=40)),
                ('sueldo', models.FloatField()),
                ('usuario', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
                ('cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='desembolso',
            fields=[
                ('id_desembolso', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total', models.FloatField(unique=True)),
                ('codigo_cuenta_cheque', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
                ('id_prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='cobro',
            fields=[
                ('id_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_total', models.FloatField()),
                ('monto_interes', models.FloatField()),
                ('monto_capital', models.FloatField()),
                ('estado', models.CharField(max_length=40)),
                ('id_prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('anio', models.CharField(max_length=40)),
                ('placa', models.CharField(max_length=40)),
                ('chasis', models.CharField(max_length=40)),
                ('id_garantia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_gestion.garantia')),
            ],
        ),
    ]
