# Generated by Django 4.1.5 on 2023-01-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informacion',
            fields=[
                ('id_informacion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_persona', models.IntegerField(unique=True)),
                ('tipo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=128)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=80, unique=True)),
                ('primer_apellido', models.CharField(max_length=40)),
                ('segundo_apellido', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('id_persona', models.IntegerField()),
                ('estado', models.CharField(max_length=40)),
                ('monto', models.FloatField()),
                ('tasa', models.FloatField()),
                ('cuota', models.IntegerField()),
            ],
        ),
    ]
